### PR TITLE
Miscellaneous additions

### PR DESCRIPTION
**Pull request by DarkmatterVale**
This PR does a couple of things, each of which described below.

1) A settings file. Currently, it saves the path to the script the user most recently opens and when the application starts automatically opens that script.
2) Prepare for localization. HaikuPlot should now be ready to be localized.

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
Please note, this PR requires #8 to be merged first

**Comment by scottmc** [comment]
Please also update the image that shows in the readme.md file so that it is transparent to the right of the tab, that way it can be used for the HaikuDepot image.

**Comment by DarkmatterVale** [comment]
@scottmc Is it correct now? I changed the background color & cut off the edges removing the blue outline.

**Comment by humdingerb** [comment]
@DarkmatterVale , the background should be transparent. It's really easy if you take the screenshot in Haiku with the PRINT key. The Screenshot app can automatically grab the active window and removes the background besides the yellow title tab. Make sure not to capture the mouse pointer.

**Comment by DarkmatterVale** [comment]
Sorry for the issues with the images, I've fixed them now.

**Pull request merged**
